CREATE TABLE Clientes (
clienteID BIGSERIAL PRIMARY KEY,
nombre VARCHAR(40) NOT NULL,
email VARCHAR(200) NOT NULL,
cell VARCHAR(15) NOT NULL,
servicio VARCHAR(80)NOT NULL,
plazo VARCHAR(30)NOT NULL,
mensaje TEXT NOT NULL,
contacted BOOLEAN NOT NULL DEFAULT false,
created_at TIMESTAMPTZ NOT NULL DEFAULT now()

);